// <auto-generated />
using System;
using ExpenseTracker.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ExpenseTracker.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251217023115_CreateBudgetsTable")]
    partial class CreateBudgetsTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ExpenseTracker.Data.Models.Budget", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("CurrentSpending")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("EndDate")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Period")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Budgets");
                });

            modelBuilder.Entity("ExpenseTracker.Data.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("KeywordsJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "#dc3545",
                            CreatedDate = new DateTime(2025, 12, 17, 2, 31, 14, 591, DateTimeKind.Local).AddTicks(4977),
                            Description = "Restaurants, groceries, coffee shops",
                            Icon = "bi-cup-straw",
                            KeywordsJson = "[\"restaurant\",\"food\",\"dinner\",\"lunch\",\"coffee\",\"grocery\"]",
                            ModifiedDate = new DateTime(2025, 12, 17, 2, 31, 14, 591, DateTimeKind.Local).AddTicks(5033),
                            Name = "Food & Dining",
                            Type = 0
                        },
                        new
                        {
                            Id = 2,
                            Color = "#007bff",
                            CreatedDate = new DateTime(2025, 12, 17, 2, 31, 14, 591, DateTimeKind.Local).AddTicks(5042),
                            Description = "Gas, public transport, ride sharing",
                            Icon = "bi-car-front",
                            KeywordsJson = "[\"gas\",\"fuel\",\"uber\",\"taxi\",\"bus\",\"train\",\"metro\"]",
                            ModifiedDate = new DateTime(2025, 12, 17, 2, 31, 14, 591, DateTimeKind.Local).AddTicks(5044),
                            Name = "Transportation",
                            Type = 0
                        },
                        new
                        {
                            Id = 3,
                            Color = "#ffc107",
                            CreatedDate = new DateTime(2025, 12, 17, 2, 31, 14, 591, DateTimeKind.Local).AddTicks(5048),
                            Description = "Clothing, electronics, household items",
                            Icon = "bi-bag",
                            KeywordsJson = "[\"shopping\",\"clothes\",\"electronics\",\"amazon\",\"store\"]",
                            ModifiedDate = new DateTime(2025, 12, 17, 2, 31, 14, 591, DateTimeKind.Local).AddTicks(5050),
                            Name = "Shopping",
                            Type = 0
                        },
                        new
                        {
                            Id = 4,
                            Color = "#20c997",
                            CreatedDate = new DateTime(2025, 12, 17, 2, 31, 14, 591, DateTimeKind.Local).AddTicks(5055),
                            Description = "Movies, streaming services, concerts",
                            Icon = "bi-film",
                            KeywordsJson = "[\"movie\",\"netflix\",\"concert\",\"game\",\"entertainment\"]",
                            ModifiedDate = new DateTime(2025, 12, 17, 2, 31, 14, 591, DateTimeKind.Local).AddTicks(5056),
                            Name = "Entertainment",
                            Type = 0
                        },
                        new
                        {
                            Id = 5,
                            Color = "#28a745",
                            CreatedDate = new DateTime(2025, 12, 17, 2, 31, 14, 591, DateTimeKind.Local).AddTicks(5060),
                            Description = "Regular employment income",
                            Icon = "bi-cash-stack",
                            KeywordsJson = "[\"salary\",\"paycheck\",\"income\"]",
                            ModifiedDate = new DateTime(2025, 12, 17, 2, 31, 14, 591, DateTimeKind.Local).AddTicks(5062),
                            Name = "Salary",
                            Type = 1
                        },
                        new
                        {
                            Id = 6,
                            Color = "#28a745",
                            CreatedDate = new DateTime(2025, 12, 17, 2, 31, 14, 591, DateTimeKind.Local).AddTicks(5066),
                            Description = "Freelance work and contract income",
                            Icon = "bi-laptop",
                            KeywordsJson = "[\"freelance\",\"contract\",\"project\"]",
                            ModifiedDate = new DateTime(2025, 12, 17, 2, 31, 14, 591, DateTimeKind.Local).AddTicks(5067),
                            Name = "Freelance",
                            Type = 1
                        });
                });

            modelBuilder.Entity("ExpenseTracker.Data.Models.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRecurring")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("RecurringEndDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("RecurringType")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("ExpenseTracker.Data.Models.Budget", b =>
                {
                    b.HasOne("ExpenseTracker.Data.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Category");
                });

            modelBuilder.Entity("ExpenseTracker.Data.Models.Transaction", b =>
                {
                    b.HasOne("ExpenseTracker.Data.Models.Category", "Category")
                        .WithMany("Transactions")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("ExpenseTracker.Data.Models.Category", b =>
                {
                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
